### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by tomoyanonymous** [mimium-org/mimium#8]
Under investigation.
With Visual Studio 2019/Clang - failed
With MinGW(GCC9.2)- failed because of thread support?
With msys2 - ?

## Problem

- hard to find llvm in CMake. find_package() could not be used because the pre-built binary(both downloaded from llvm.org and chocolatey) does not have Findxxx.cmake file. also, llvm-config does not exist for windows. Even if we could built manually, how can we manage it in CI?
- which CMake generator is appropriate - VS or Ninja?
- maybe, can we cross compile into mingw on Linux?

**Comment by mocabe** [comment]
How about using package manager? For example, [vcpkg](https://github.com/microsoft/vcpkg) supports wide range of libraries including `llvm` and `libsndfile`. Not sure that meets your requirements, though.

**Comment by tomoyanonymous** [comment]
Thanks for suggestion! I have never tried vcpkg but llvm in vcpkg seems the package is built from source and nice to use with `find_package` in cmake.
I will make a branch for windows build and later try on it.

**Comment by mocabe** [comment]
Just FYI, I recently made tiny sample using `vcpkg` and `CMake`. You can clone [this repo](https://github.com/mocabe/vcpkg-test) and play around with it.
